// the shape of data we expect between the browser and the server

import type { Lifx } from './lifx'

export interface DiscoveredDevice {
  mac: string
  ip: string
  port: number
  // false = known from persisted store but not seen in this discovery run
  detected?: boolean
}

// ---------------------------------------------------------------------------
// POST /devices/:mac/state — discriminated body. The discriminator lives in
// the body, not the URL, so the route surface stays small as more device
// fields land. `commandId` is generated by the client; the server echoes it
// back through the SSE stream as `origin` on the resulting device_field
// event so a tab can match its own command's echo against foreign updates.
// ---------------------------------------------------------------------------

export type DeviceStateCommand =
  | { commandId: string; field: 'color';    value: Lifx.Application.Hsbk; duration?: number }
  | { commandId: string; field: 'label';    value: string }
  | { commandId: string; field: 'group';    value: string }
  | { commandId: string; field: 'location'; value: string }
  | { commandId: string; field: 'power';    value: boolean; duration?: number }

export interface DeviceActionCommand {
  commandId: string
}
